name: skUtilities
description: An addon for skript that adds conversions, utilities, files and much more.
author: Equipable, tim740
website: https://github.com/EquipableMC/skUtilities
main: uk.tim740.skUtilities.skUtilities
version: 0.9.2
depend: [Skript]