name: skUtilities
description: An addon for skript that adds conversions, utilities, files and much more.
api-version: '1.13'
author: Equipable, tim740
website: https://github.com/EquipableMC/skUtilities
main: uk.tim740.skUtilities.skUtilities
version: @version@
depend: [Skript]